### ISSUE TITLE
error in CRT

### ISSUE THREAD

**Issue by Achuan-2** [dnasko/CASC#11]
```shell
(achuan) 04_NBT $ bash /mnt/raid7/Dachuang/Achuan/biosoft/CASC/bin/CRT ${HOST_DB}/2061766007_55.fna /mnt/raid7/Dachuang/Achuan/04_NBT/02_CRISPR_casc/2061766007_55
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: org/biojavax/bio/seq/RichSequence$IOTools
        at FASTAReader.<init>(FASTAReader.java:19)
        at CRISPRFinder.goCRISPRFinder(CRISPRFinder.java:96)
        at crt.main(crt.java:210)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: org.biojavax.bio.seq.RichSequence$IOTools
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.bas
```

**Comment by Achuan-2** [comment]
java version problem·

`conda install openjdk=8.0.121 `sovle it
